# Generated by Django 5.0.4 on 2024-04-16 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cat', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reting_aut', models.SmallIntegerField(default=0)),
                ('autor_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articles_or_news', models.CharField(choices=[('AR', 'Статья'), ('NE', 'Новость')], default='AR', max_length=2)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('rating_pos', models.IntegerField(choices=[('on', 1), ('tw', 2), ('th', 3), ('fo', 4), ('fi', 5), ('si', 6), ('se', 7), ('ei', 8), ('ni', 9), ('te', 10)], default=0)),
                ('post_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sapp.autor')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_com', models.TextField()),
                ('datetimecom', models.DateTimeField(auto_now_add=True)),
                ('reting_com', models.IntegerField(default=0)),
                ('comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comment_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sapp.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcategory_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sapp.category')),
                ('postcategory_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sapp.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='post_catagory',
            field=models.ManyToManyField(through='sapp.PostCategory', to='sapp.category'),
        ),
    ]
